image: fbe-dockerreg.rwu.de/doz-iki/amr-vl

before_script:
  - sleep 5
  - source /root/catkin_ws/devel/setup.bash

stages:
    - catkin make

catkin make:
    stage: catkin make
    script:
    - roscd; cd ..; catkin_make
